### ISSUE TITLE
GoDocs doesn't recognize license

### ISSUE THREAD

**Issue by droberts-sea** [elliotchance/mocksqs#12]
Visiting the godocs page for this repo, as linked from the README: https://pkg.go.dev/github.com/elliotchance/mocksqs

Yields this:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/21064499/123180272-d1092e00-d43f-11eb-936f-d5df3f4ac810.png">

Looks like this repo does not have a license, so the solution would be to add one.

**Comment by elliotchance** [comment]
Thanks for reminding me, should be good now.
